### ISSUE TITLE
graph != tree

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#123]
Since we may start writing more concrete examples, possibly in YAML #122, I think we should keep in mind the graph structure of data and avoid seeing it as tree. For example @ahdinosaur wrote 
snippet:
```yaml
'@type': vf:Transportation
resource: ex:resource/those-delicious-crates-of-apples-i-got-while-dumpster-diving
dimension: 20
start: ex:locations/the-zig-zag
end: ex:locations/the-lowlands
process:
  '@type': vf:Process
  inputs:
    - '@type': vf:Consume
      resource: ex:resources/coop-petrol
      dimension: 1 L
    - '@type': vf:Use
      resource: ex:resource/coop-vehicle
      dimension: 1
```

we should consider it **equal** to

```yaml
'@type': vf:Process
inputs:
  - '@type': vf:Consume
    resource: ex:resources/coop-petrol
    dimension: 1 L
  - '@type': vf:Use
    resource: ex:resource/coop-vehicle
    dimension: 1
'@reverse':
  process:
    '@type': vf:Transportation
    resource: ex:resource/those-delicious-crates-of-apples-i-got-while-dumpster-diving
    dimension: 20
    start: ex:locations/the-zig-zag
    end: ex:locations/the-lowlands
```

Both after parsing will have identical serialization and when serialized using [RDF Dataset Normalization](http://json-ld.github.io/normalization/spec/) will produce identical documents with the same checksum (hash). If someone needs particular shape of JSON, than one can use [JSON-LD Framing](http://json-ld.org/spec/latest/json-ld-framing/) but in my opinion we shouldn't privilege any particular frame and always rely directly on the structure of represented graph.
