### ISSUE TITLE
Agreement Template

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#266]
Capturing quickly from: https://github.com/valueflows/valueflows/issues/261#issuecomment-355834405

> I think reusable Agreement Recipe would cover cases like: https://en.wikipedia.org/wiki/List_price

While process recipes rely on physical dynamics, agreement recipes rely on social dynamics. This may imply that without implications of physical constraints, they may not come as 'reusable'. Example of *List price* seems to give at least one case for reusing such *Agreement Recipe* by many agents.

**Comment by fosterlynn** [comment]
>Could you maybe share in #266 the use case with '3 transfer types' from Sensorica?

Exchange Type: Purchase
    Transfer Type: Receipt (of material items)
    Transfer Type: Expense (other costs of getting the material items)
    Transfer Type: Payment

(Note the terms Purchase, Receipt, Expense, and Payment are user defined.)

**Comment by elf-pavlik** [comment]
could you please also write quickly all events for a observed exchange based on that recipe?

**Comment by fosterlynn** [comment]
>could you please also write quickly all events for a observed exchange based on that recipe?

![exch-vf-ex](https://user-images.githubusercontent.com/3776081/34654356-3fef9d0e-f3c0-11e7-9d82-c21f73c0cbe6.png)

Somewhat confusing, not sure why they have both Expense and Additional Expense in the exchange type.

**Comment by elf-pavlik** [comment]
> could you please also write quickly all events for a observed exchange based on that recipe? Including provider & recipient relations for those events.

On your screenshot I have impression that you have 3 agents:
* ORD solutions
* Digital Fab services
* Tibi

Does this record 3 way exchage betwen those 3 agents or 2 way and Tibi represents Digital Fab here?

Those agents mostly appear on Recipt and two Pay Purchase, and expense has only *receive* so no info who *give* there.

I asked for events with *provider* and *recipient* information since most likely that provides all the information to infer all the reciprocity details in the exchange under this agreement.

If we take an example of https://en.wikipedia.org/wiki/List_price expressed as an *Agreement Recipe* published by some vendor - eg. "1 bushel of apples for 30 faircoins". The retailer would use that recipe and 'bind' / 'substitute' onself as *provider* on intent to *issue* apples and *recipient* on intent to *receive* faircoins. The customer could also use the same recipe and 'bind' / 'substitute' onaself as *provider* on intent to *receive* faircoins and *recipient* on event to *issue* apples. Possibly for that case a single action like *acquire* would work better than *issue* & *receive* so the same recipe could work for both pick-up and delivery cases.

Pseudo *Agreement Recipe*:
* *Agreement Recipe*
  * *Flow Recipe* - issue: apples n*1 bushels, provider: ?retailer, recipient: ?customer 
  * *Flow Recipe* - receive: n*30 faircoins, provider: ?customer, recipient: ?retailer

n* means value can scale by factor n
? means a variable for binding / substitution

Later when the transaction happen, we would have practically the same 'shape' as in such recipe:
* *Agreement*
  * *Flow Event* - issue: apples 5 bushels, provider: retailer-123, recipient: customer-456 
  * *Flow Event* - receive: 150 faircoins, provider: customer-456, recipient: retailer-123

To hint possibility of *Agreement Template*, if retailer-123 and customer-456 make more specific arrangement than the general *Agreement Recipe* issued by the vendor, they could pre 'bind' / 'substitute' variable for agents, and it still will have pretty much the same 'shape'

* *Agreement Template*
  * *Flow Template* - issue: apples n*1 bushels, provider: retailer-123, recipient: customer-456
  * *Flow Template* - receive: n*25 faircoins, provider: customer-456, recipient: retailer-123

So it still has n* scaling points like in recipe, but already has pre 'bound' / 'substituted' agents like in event or commitment.

**Comment by fosterlynn** [comment]
>Those agents mostly appear on Recipt and two Pay Purchase, and expense has only receive so no info who give there.

Yeah, the expense should be to Digital Fab Services, who got the benefit of the shipping service.  Data entry error, probably, and I see a few others too.

I think what happened was they paid for the printer from the account where people had contributed, so Digital Fab Services to ORD, then they found out they had to ship because someone's dad couldn't pick it up, so Tibi paid for the shipping (maybe as a contribution to be repaid later, I don't know).

This is just an example where there are more than 2 transfer types in one exchange type, which is what you were looking for.

The agents recorded will eventually make it clear what is going on, but at the recipe level I think it would be confusing if you can't immediately tell what reciprocity is intended.

**Comment by elf-pavlik** [comment]
> The agents recorded will eventually make it clear what is going on, but at the recipe level I think it would be confusing if you can't immediately tell what reciprocity is intended.

In the examples I provided for List Price, with retailer and customer. I think one can tell expected reciprocity in the recipe the same one one tells it in the observation - from *provider* / *recipient* relation to variables / placeholders for agents. And in my example both retailers and customers could reuse the same recipe published by the vendor and just bind oneself to different variable / placeholder in the recipe.

**Comment by fosterlynn** [comment]
>In the examples I provided for List Price, with retailer and customer.

Yes, defined agent relationship roles can help with that, if we want to bring that into the model there.  Especially when there are obvious roles like retailer and customer.  When you have peer relationships like for straight barter, I'm not sure how that would work.  (The same problem as we have with "reciprocal transfer", what do you do when there isn't a "primary" reason for the transfer.)

**Comment by fosterlynn** [comment]
>To hint possibility of Agreement Template, if retailer-123 and customer-456 make more specific arrangement than the general Agreement Recipe issued by the vendor, they could pre 'bind' / 'substitute' variable for agents, and it still will have pretty much the same 'shape'

Would you not consider this an Intent?

**Comment by elf-pavlik** [comment]
> Would you not consider this an Intent?

I don't think Flow Intent should allow scaling it any more, I think we get intents after scaling the whole recipe or template.

**Comment by fosterlynn** [comment]
>I don't think Flow Intent should allow scaling it any more, I think we get intents after scaling the whole recipe or template.

Ah I understand the difference now.  Do you think templates should be part of the vocabulary, or not?  And if so, would you like to address them now, or later?

**Comment by elf-pavlik** [comment]
I see them together with recipes for agreements. While in the *Agreement Recipe* one would only use *vf:provider* and *vf:recipient* with such 'variables' / 'placeholders' for agents, in *Agreement Template* one could already have *vf:provider* and *vf:recipient* referencing actual agents.

Offers / Request might actually need such templates and not use recipes directly. Otherwise how agent making offer / request would specify where it wants to act as *provider* and where as *recipient* in Flow Recipe instances used in that offer / request ?

**Comment by fosterlynn** [comment]
>provider: ?retailer, recipient: ?customer

>I didn't mention any 'agent relationship roles', just 'variables' / 'placeholders' used with vf:provider and vf:reciver in recipes and templates

retailer and customer are agent relationship roles, no?

**Comment by fosterlynn** [comment]
>retailer and customer are agent relationship roles, no?

Actually, more like label/inverse label of one role I suppose.  I think the idea has possibilities, I'll try to work it into the model.  (Although I don't quite understand why separating something like transfer and reciprocal transfer is a problem - or whatever better names we can come up with.)

**Comment by elf-pavlik** [comment]
> retailer and customer are agent relationship roles, no?

no, just 'variables' / 'placeholder', examples i provided would work the same if i called variables *alice* & *bob* or *foo* & *bar*, what matters that in the same recipe or template we use the same 'variable' / 'placeholder' where we expect the same agent in agreement made based on that recipe or template.

**Comment by elf-pavlik** [comment]
```yaml
'@context':
  - https://w3id.org/valueflows/v1
  - wd: https://www.wikidata.org/entity/
  - vendor: https://vendor.example/

'@graph':
  - '@id': vendor:recipe/agreement/jonagold-for-faircoin
    '@type': vf:AgreementRecipe
    'vf:classifiedAs': wd:Q601401 # Trade
  - '@id': vendor/recipe/agent-slots/84327
    '@type': vf:AgentSlot
  - '@id': vendor/recipe/agent-slots/95302
    '@type': vf:AgentSlot
  - '@id': vendor:recipe/flow/12345
    '@type': vf:FlowRecipe
    'vf:under': vendor:recipe/agreement/jonagold-for-faircoin
    'vf:action': vf:issue
    'vf:resourceClassifiedAs': wd:Q494417 # Jonagold apple
    'vf:scalableQuantity':
      '@type': qudt:QuantityValue
      'qudt:unit': wd:Q32750816 # Bushel (US)
      'qudt:numericValue': 1
    'vf:provider': vendor/recipe/agent-slots/84327
    'vf:recipient': vendor/recipe/agent-slots/95302
  - '@id': vendor:recipe/flow/67890
    '@type': vf:FlowRecipe
    'vf:under': vendor:recipe/agreement/jonagold-for-faircoin
    'vf:action': vf:receive
    'vf:resourceClassifiedAs': wd:Q21002847 # Faircoin
    'vf:scalableQuantity':
      '@type': qudt:QuantityValue
      'qudt:unit': ???:each
      'qudt:numericValue': 30
    'vf:provider': vendor/recipe/agent-slots/95302
    'vf:recipient': vendor/recipe/agent-slots/84327
```

Please notice the two instances of `vf:AgentSlot`, each appearing related once with *vf:provider* and other times with *vf:recipient* from *vf:FlowRecipe*

**Comment by fosterlynn** [comment]
>Please notice the two instances of vf:AgentSlot, each appearing related once with vf:provider and other times with vf:recipient from vf:FlowRecipe

Yes, I understand, thanks!  And great to see some yaml! :smile: 

I gotta say, I find the slots very confusing in terms of defining a vocabulary.  It seems like a workable programming technique, but having arbitrarily defined slots with an identity but no meaning doesn't really sit well for me as making a clear vocabulary.

I do like the effort to eliminate that middle "transfer" thing though, and go straight to the flow spot (although the name can be useful, so I'm not sure about that).  Maybe we can do it like "inputOf"/"outputOf", but figure out some names that don't have to imply the one is primary and the other is reciprocal - and do it as properties/relationships instead of an actual class.  It wouldn't have to be an agent placeholder then.  (As you saw in the Sensorica example, it won't always be just 2 agents, and it won't be predictable.)

I'll think some more and try some yaml later today.

**Comment by elf-pavlik** [comment]
@fosterlynn let's already take into account multilateral agreements for exchanges where we don't always have direct reciprocity between flows https://github.com/valueflows/exchange/issues/19 and https://github.com/valueflows/valueflows/issues/246#issuecomment-346944165

**Comment by elf-pavlik** [comment]
> I think reusable Agreement Recipe would cover cases like: https://en.wikipedia.org/wiki/List_price

Another interesting use case for reusable Agreement Recipe - many work exchange platforms - WWOOF, HelpX, Workaway... recommend something like:

* work 20h in one week
* food + accommodation for a week

**Comment by elf-pavlik** [comment]
As alternative to #301 I would also like to explore taking inspiration from #293 and #296 and use nested agreements. This way an agreement for *3h of work + 2h of usage* for *20l of juice* could stay composed from two sub agreements
* 3h of work for 15l of juice
* 2h of usage for 5l of juice

`vf:includedIn` should work here just fine. Then each of those sub agreements can come from a recipe for exchange which would provide alternative for exchange rates.

The main difference come that here *provider* and *recipient* matters unlike in process recipes.

**Comment by elf-pavlik** [comment]
I think I like Agreement Recipe more than Exchange Rate, it follows the same approach as Process Recipe from #296 and `vf:RecipeFlow` contains quantity and unit that get scaled.

```yaml
`@context': ...
`@graph`:

  - `@id`: ex:alice
    `@type`: foaf:Person

  - `@id`: ex:work-agreement-recipe
    `@type`: AgreementRecipe

  - `@id`: ex:usage-agreement-recipe
    `@type`: AgreementRecipe

  - `@id`: ex:work-intent
    `@type`: Intent
    provider: ex:alice
    action: work
    quantity:
      'qudt:numericValue': 100
      `qudt:unit`: unit:Hour

 - `@id`: ex:work-recipe
    `@type`: RecipeFlow
    action: work
    quantity:
      'qudt:numericValue': 1
      `qudt:unit`: unit:Hour
    under: ex:work-agreement-recipe

  - `@id`: ex:use-intent
    `@type`: Intent
    provider: ex:alice
    action: use
    affects: ex:some-tool
    quantity:
      'qudt:numericValue': 200
      `qudt:unit`: unit:Hour

  - `@id`: ex:use-recipe
    `@type`: RecipeFlow
    action: use
    affects: ex:some-tool
    quantity:
      'qudt:numericValue': 1
      `qudt:unit`: unit:Hour
    under: ex:usage-agreement-recipe

  - `@id`: ex:issue-intent
    `@type`: Intent
    action: issue
    recipient: ex:alice
    affectedClassifiedAs: http://www.wikidata.org/entity/Q618355 # apple juice
    quantity:
      'qudt:numericValue': 30
      `qudt:unit`: unit:Liter 

  - `@id`: ex:issue-recipe-work
    `@type`: RecipeFlow
    action: issue
    affectedClassifiedAs: http://www.wikidata.org/entity/Q618355 # apple juice
    quantity:
      'qudt:numericValue': 5
      `qudt:unit`: unit:Liter 
    under: ex:work-agreement-recipe

  - `@id`: ex:issue-recipe-usage
    `@type`: RecipeFlow
    action: issue
    affectedClassifiedAs: http://www.wikidata.org/entity/Q618355 # apple juice
    quantity:
      'qudt:numericValue': 2.5
      `qudt:unit`: unit:Liter
  under: ex:usage-agreement-recipe

  - `@id`: ex:a-proposal
    `@type`: Proposal
    eligibleIntent:
      - ex:work-intent
      - ex:issue-intent
    applicableRecipes: ex:an-agreement-recipe

  - `@id`: ex:another-proposal
    `@type`: Proposal
    eligibleIntent:
      - ex:use-intent
      - ex:issue-intent
    applicableRecipes: ex:another-agreement-recipe
```

This would lead to exchange (most likely with prior commitments):
```yaml
`@context': ...
`@graph`:

  - `@id`: ex:an-agreement
    `@type`: Agreement

  - `@id`: ex:sub-agreement-work
    `@type`: Agreement

  - `@id`: ex:sub-agreement-usage
    `@type`: Agreement

  - `@id`: ex:work-event
    `@type`: EconomicEvent
    under:
      - ex:an-agreement
      - ex:sub-agreement-work
    action: work
    quantity:
      'qudt:numericValue': 3
      `qudt:unit`: unit:Hour

  - `@id`: ex:use-event
    `@type`: EconomicEvent
    under:
      - ex:an-agreement
      - ex:sub-agreement-usage
    action: use
    affects: ex:some-tool
    quantity:
      'qudt:numericValue': 2
      `qudt:unit`: unit:Hour

  - `@id`: ex:issue-event
    `@type`: EconomicEvent
    under: ex:an-agreement
    action: issue
    affectedClassifiedAs: http://www.wikidata.org/entity/Q618355 # apple juice
    quantity:
      'qudt:numericValue': 20
      `qudt:unit`: unit:Liter 

  - `@id`: ex:issue-event-for-work
    `@type`: EconomicEvent
    under: ex:sub-agreement-work
    action: issue
    affectedClassifiedAs: http://www.wikidata.org/entity/Q618355 # apple juice
    quantity:
      'qudt:numericValue': 15
      `qudt:unit`: unit:Liter
    includedIn: ex:issue-event 

  - `@id`: ex:issue-event-for-usage
    `@type`: EconomicEvent
    under: ex:sub-agreement-usage
    action: issue
    affectedClassifiedAs: http://www.wikidata.org/entity/Q618355 # apple juice
    quantity:
      'qudt:numericValue': 5
      `qudt:unit`: unit:Liter
    includedIn: ex:issue-event 
```
