### ISSUE TITLE
Example: use of drills (shared tools)

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#394]
From the UC https://github.com/valueflows/valueflows/wiki/Use-Cases-and-Requirements#shared-tools

>Local community maintains a shed where they keep shared tools. They maintain each category of tools as one resource with certain number of items in it. People can use those tools, for example:
>    Use 5 electric drills (out of 23 in total) for 3 hours

(Doing this as an issue, as it is a bit obscure for a published example and may have many opinions.)

```yaml
'@context':
  '@vocab': https://w3id.org/valueflows#
  xsd: http://www.w3.org/2001/XMLSchema#
  qudt: http://qudt.org/schema/qudt/
  unit: http://qudt.org/vocab/unit/
  time: http://www.w3.org/2006/time#
  time:inXSDDateTimeStamp:
    '@type': xsd:dateTimeStamp
  alice: https://alce.example/
  bob: https://bob.example/
  carpenters: https://local-carpenters.example/
  community: https://community-tools.example/

'@graph':

  - '@id': community:60f4204e-b8d2-4026-8577-102c3f82c0af
    '@type': EconomicResource
    skos:note: Drills
    currentQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 23

  - '@id': community:6405b8ad-0ac2-4d58-abdb-08089342abcd
    '@type': Transfer
    skos:note: carpenters borrow drills from community tool lending library

  - '@id': community:6405b8ad-0ac2-4d58-abdb-0808903c78ad
    '@type': EconomicEvent
    inputOf: community:6405b8ad-0ac2-4d58-abdb-08089342abcd
    action: give
    provider: community
    receiver: carpenters
    affects:community:60f4204e-b8d2-4026-8577-102c3f82c0af
    observedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 5
    observedTime:
      time:intervalStarts:
        time:inXSDDateTimeStamp: 2019-01-02T02:10:43.003-5:00
      time:intervalEnds:
        time:inXSDDateTimeStamp: 2019-01-02T02:10:43.003-5:00

  - '@id': carpenters:6453b8ad-0ac2-4d58-abdb-0808903c78ad
    '@type': EconomicEvent
    outputOf: community:6405b8ad-0ac2-4d58-abdb-08089342abcd
    action: receive
    provider: community
    receiver: carpenters
    affects: carpenters:6453b8ad-b8d2-4026-8577-102c3f934877
    observedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 5
    observedTime:
      time:intervalStarts:
        time:inXSDDateTimeStamp: 2019-01-02T02:10:43.003-5:00
      time:intervalEnds:
        time:inXSDDateTimeStamp: 2019-01-02T02:10:43.003-5:00

  - '@id': carpenters:6453b8ad-b8d2-4026-8577-102c3f934877
    '@type': EconomicResource
    skos:note: Borrowed drills
    currentQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 5

  - '@id': carpenters:60f4204e-b8d2-4026-8577-42998fe0922a
    '@type': EconomicResource
    skos:note: Usage of 5 borrowed drills
    underlyingResource: carpenters:60f4204e-b8d2-4026-8577-102c3f82c0af

  - '@id': carpenters:8e5fe80d-a769-4bd5-89e5-2136d33eab9f
    '@type': Process
    skos:note: Make wooden cart

  - '@id': carpenters:6405b8ad-0ac2-4d58-abdb-23987320002
    '@type': EconomicEvent
    action: use
    affects: carpenters:60f4204e-b8d2-4026-8577-102c3f82c0af
    inputOf: carpenters:8e5fe80d-a769-4bd5-89e5-2136d33eab9f
    observedQuantity:
      qudt:unit: unit:Hour
      qudt:numericValue: 3

    # .....

  - '@id': community:6405b8ad-0ac2-4d58-abdb-080893429876
    '@type': Transfer
    skos:note: carpenters return drills to community tool lending library

  - '@id': carpenters:6405b8ad-0ac2-4d58-abdb-0808903c7453
    '@type': EconomicEvent
    inputOf: community:6405b8ad-0ac2-4d58-abdb-080893429876
    action: give
    provider: carpenters
    receiver: community
    affects:carpenters:6453b8ad-b8d2-4026-8577-102c3f934877
    observedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 5
    observedTime:
      time:intervalStarts:
        time:inXSDDateTimeStamp: 2019-01-02T05:10:43.003-5:00
      time:intervalEnds:
        time:inXSDDateTimeStamp: 2019-01-02T05:10:43.003-5:00

  - '@id': community:6453b8ad-0ac2-4d58-abdb-0808903cd34a
    '@type': EconomicEvent
    outputOf: community:6405b8ad-0ac2-4d58-abdb-080893429876
    action: receive
    provider: carpenters
    receiver: community
    affects: community:60f4204e-b8d2-4026-8577-102c3f82c0af
    observedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 5
    observedTime:
      time:intervalStarts:
        time:inXSDDateTimeStamp: 2019-01-02T05:10:43.003-5:00
      time:intervalEnds:
        time:inXSDDateTimeStamp: 2019-01-02T05:10:43.003-5:00
```

**Comment by elf-pavlik** [comment]
```yaml
- '@id': carpenters:6405b8ad-0ac2-4d58-abdb-23987320002
    '@type': EconomicEvent
    action: use
    affects: carpenters:60f4204e-b8d2-4026-8577-102c3f82c0af
    inputOf: carpenters:8e5fe80d-a769-4bd5-89e5-2136d33eab9f
    observedQuantity:
      qudt:unit: unit:Hour
      qudt:numericValue: 3
```

How they can note how many drills they have actually used, in your scenario they could 'receive' possession of 5 but in the end only used 3. I would prefer to leave all the 'rights and responsibilities' concerns to #148 and here start with assumption that 'carpenters' can without any conversation for action make commitments to *use* number of drills on specific time as long as someone else haven't already made conflicting commitment. So if two other commitments exist for desired period of time, for 7 drills and 8 drills, they can make commitment for 5 and still someone else could make commitment for up to 3 (which would reach 23 total).
Could you write how you would see
* Commitment to *use* 5 drills during specific (proper) time interval, directly involving community:60f4204e-b8d2-4026-8577-102c3f82c0af
* Event of *use* 5 drills during specific (proper) time interval, directly affecting community:60f4204e-b8d2-4026-8577-102c3f82c0af

Or you consider defining *use* as:
"One always has to use **all the current quantity of the resource** and if needed *split* desired quantity first into separate resource and then use **all of that separate resource**" ?

Myself I see some problems with this approach
* to know how many electric drills were used one has to rely on calculating *currentQuantity* of affected resource and don't have that information directly on event
* one has to make separate commitment to first *split* quantity of a resource and then to *use* that split resoruce
* record of usage get spread across a lot of temporary resources created only for the sake of adjusting quantity for *use* event, to aggregated all the actual history of *usage* one has to go over all the split and merge operations and add *use* on those temporary resources

**Comment by elf-pavlik** [comment]
>* Commitment to use 5 drills during specific (proper) time interval, directly involving community:60f4204e-b8d2-4026-8577-102c3f82c0af
>* Event of use 5 drills during specific (proper) time interval, directly affecting community:60f4204e-b8d2-4026-8577-102c3f82c0af

```yaml
'@context':
  '@vocab': https://w3id.org/valueflows#
  xsd: http://www.w3.org/2001/XMLSchema#
  qudt: http://qudt.org/schema/qudt/
  unit: http://qudt.org/vocab/unit/
  time: http://www.w3.org/2006/time#
  time:inXSDDateTimeStamp:
    '@type': xsd:dateTimeStamp
  carpenters: https://local-carpenters.example/
  community: https://community-tools.example/

'@graph':

  - '@id': community:60f4204e-b8d2-4026-8577-102c3f82c0af
    '@type': EconomicResource
    skos:note: Drills
    currentQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 23

  - '@id': community:e0462952-0fa6-4508-9d28-d9abc3a7d7e3
    '@type': Commitment
    action: use
    inolves: community:60f4204e-b8d2-4026-8577-102c3f82c0af
    committedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 5
    committedTime:
      time:intervalStarts:
        time:inXSDDateTimeStamp: 2010-10-14T12:00:00-5:00
      time:intervalEnds:
        time:inXSDDateTimeStamp: 2018-10-14T15:00:00-5:00
    provider: community
    receiver: carpenters

  - '@id': carpenters:6d1979eb-4d64-41fc-8b6f-800e0032303d
    '@type': EconomicEvent
    action: use
    affects: community:60f4204e-b8d2-4026-8577-102c3f82c0af
    observedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 5
    observedTime:
      time:intervalStarts:
        time:inXSDDateTimeStamp: 2010-10-14T12:00:00-5:00
      time:intervalEnds:
        time:inXSDDateTimeStamp: 2018-10-14T15:00:00-5:00
    provider: community
    receiver: carpenters

  - '@id': carpenters:e506ce20-6c41-4327-9312-73f6fc4537dc
    '@type': Fulfillment
    fulfills: community:e0462952-0fa6-4508-9d28-d9abc3a7d7e3
    fulfilledBy: carpenters:6d1979eb-4d64-41fc-8b6f-800e0032303d
    fulfilledQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 5
    fulfilledTime:
      time:intervalStarts:
        time:inXSDDateTimeStamp: 2010-10-14T12:00:00-5:00
      time:intervalEnds:
        time:inXSDDateTimeStamp: 2018-10-14T15:00:00-5:00

```

**Comment by fosterlynn** [comment]
>I would prefer to leave all the 'rights and responsibilities' concerns to #148 and here start with assumption that 'carpenters' can without any conversation for action make commitments to use number of drills on specific time as long as someone else haven't already made conflicting commitment.

That seems like a different use case, but OK - since this is to figure out the best way to handle quantities of a material resource vs quantities recorded about the use of that resource.  So maybe not a lending library, more like a bunch of tools in a shared space used by one organization, where nothing has to move between scopes of operations?

>Or you consider defining use as:
>"One always has to use all the current quantity of the resource and if needed split desired quantity first into separate resource and then use all the current quantity of that separate (temporary) resource" ?

No, I consider use to be actual use, to the degree desired by the group using the tools (nothing to do with the group lending the tools, they only care if it is gone).  Seemed like in this case if they were considering a group of drills and not bothering with the individual drills, then that didn't matter so much to them.  As always, there are lots of ways to record this stuff, depending on the needs of the agents.

>record of usage get spread across a lot of temporary resources created only for the sake of adjusting quantity for use event

Agree this is not so good.  Would be more applicable for a group that has its own drills, so could keep the underlying resource structure in place for all of its tools without the temporary phenomenon.  But I'll keep trying examples to see how this plays out, or not.

**Comment by fosterlynn** [comment]
Giving this a try as a slightly different use case to avoid transfers.  Since we haven't modeled scheduled resources, I'm not including that.  But each event could include the exact duration (in addition to the "counted" quantity) if that is important.

A group of carpenters has an inventory of various tools including 23 drills.  Some of the carpenters are working on a process that requires 3 drills for about 5 hours.

```yaml
'@context':
  '@vocab': https://w3id.org/valueflows#
  xsd: http://www.w3.org/2001/XMLSchema#
  qudt: http://qudt.org/schema/qudt/
  unit: http://qudt.org/vocab/unit/
  time: http://www.w3.org/2006/time#
  time:inXSDDateTimeStamp:
    '@type': xsd:dateTimeStamp
  alice: https://alce.example/
  bob: https://bob.example/
  carol: https://carol.example/
  carpenters: https://local-carpenters-group.example/

'@graph':

  - '@id': carpenters:60f4204e-b8d2-4026-8577-102c3f82c0af
    '@type': EconomicResource
    skos:note: Drills
    currentQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 23

  - '@id': carpenters:60f4204e-b8d2-4026-8577-42998fe0922a
    '@type': EconomicResource
    skos:note: Usage of 1 drill
    underlyingResource: carpenters:60f4204e-b8d2-4026-8577-102c3f82c0af

  - '@id': carpenters:8e5fe80d-a769-4bd5-89e5-2136d33eab9f
    '@type': Process
    skos:note: Make wooden cart

  - '@id': carpenters:6405b8ad-0ac2-4d58-abdb-23987320002
    '@type': EconomicEvent
    action: use
    affects: carpenters:60f4204e-b8d2-4026-8577-42998fe0922a
    inputOf: carpenters:8e5fe80d-a769-4bd5-89e5-2136d33eab9f
    provider: alice
    receiver: carpenters
    observedQuantity:
      qudt:unit: unit:Hour
      qudt:numericValue: 5

  - '@id': carpenters:6405b8ad-0ac2-4d58-abdb-23987320003
    '@type': EconomicEvent
    action: use
    affects: carpenters:60f4204e-b8d2-4026-8577-42998fe0922a
    inputOf: carpenters:8e5fe80d-a769-4bd5-89e5-2136d33eab9f
    provider: bob
    receiver: carpenters
    observedQuantity:
      qudt:unit: unit:Hour
      qudt:numericValue: 5

  - '@id': carpenters:6405b8ad-0ac2-4d58-abdb-23987320004
    '@type': EconomicEvent
    action: use
    affects: carpenters:60f4204e-b8d2-4026-8577-42998fe0922a
    inputOf: carpenters:8e5fe80d-a769-4bd5-89e5-2136d33eab9f
    provider: carol
    receiver: carpenters
    observedQuantity:
      qudt:unit: unit:Hour
      qudt:numericValue: 4.5

```
