### ISSUE TITLE
Resource concept and structure

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#480]
This is an issue that was spawned over in the graphql discussions, and is probably for later. But I thought I would at least record it.  And if this makes immediate sense to you @elf-pavlik , we could look at just getting it done now.  If not, that's fine too, let's wait.

Related to recent discussions about "economic resource" as a more concept-y thing with lots of nuances, and to some earlier discussions too, what do you think about moving `involves`, `resourceClassifiedAs` and `resourceConformsTo` into a structure that would be referenced from flows?  Would need to work with the names.

Something like (notation is approximate!):
```
involves:
    @type: EconomicResource
    resourceClassifiedAs: [a uri list]
    resourceConformsTo: [a ResourceSpecification]
    resourceInventoriedAs: [a InventoriedResource]
```

We can work with the names if you like the idea.  In that example, InventoriedResource would become our current EconomicResource with the same attributes.

**Comment by elf-pavlik** [comment]
If you have an instance of `EconomicResource` here, I see no reason to prefix properties with *resource*. I guess involved quantity could also go here simply as *quantity* (which that flow involves).
So in the end we will have per-flow instance of the resource, and 'InventoriedResource' becomes stocks where resources flow between?

Still for work on usage we wouldn't have instances of `EconomicResource` ?

**Comment by fosterlynn** [comment]
>If you have an instance of EconomicResource here, I see no reason to prefix properties with resource.

Good point, will change if we go forward with it.

>I guess involved quantity could also go here simply as quantity (which that flow involves).

No, that is a quantity of the flow.  This is the resource concept that the flow references.

>So in the end we will have per-flow instance of the resource, and 'InventoriedResource' becomes stocks where resources flow between?

Sort of.  Basically we would have one property to reference the resource-y information that informs the flow.  not so much an "instance of the resource".  InventoriedResource becomes what EconomicResource is now.  Your comments make me realize that it is probably a bad idea to use the term EconomicResource for stuff inside a flow, that probably wouldn't exist on its own merits.  Yes, bad idea.

>Still for work on usage we wouldn't have instances of EconomicResource ?

I was thinking that every flow would have a property that pulls together one to three of those pieces of resource information.  So then it needs a name.  But for work it might be only the resource classification or specification.  If a person's or an equipment's work or usage calendar is considered an inventoried resource in its own right, then that would be there too.

**Comment by fosterlynn** [comment]
Next iteration:
```
involves:
    @type: FlowResource
    classifiedAs: [a uri list]
    conformsTo: [a ResourceSpecification]
    inventoriedAs: [a EconomicResource]
```

Not sure this is actually a good idea, trying to get the concept across that a flow can have its resource-ness defined in many ways.

Hmmm, maybe if we drop this idea, `involves` should be `resourceInventoriedAs`.  Much more clear I think.
